### ISSUE TITLE
TypeError: Non-hexadecimal digit found

### ISSUE THREAD

**Issue by joushx** [pedro-n-rocha/bli223dcryptex#1]
Got an exception when trying to decrypt this one: http://www.herby-bauer.com/Download-Verzeichnis/Firmwares/TG588v/TG588v_r1058E_CP.zip 

Maybe a different key. Nice project btw.

```
fdata len : 0xe310b3
hdr len   : 0x169 
data len  : 0xe30f4a 
totallen  : 0xe310b3 
diffsizes : 0x0
b2mutelen : 0xe30f40 
b2posend : 0x173
ptr1dec : 0x173 
00000000: 6E 3D 49 32 14 68 9E 23  B9 C0 CA 5C CB 47 3E EA  n=I2.h.#...\.G>.
00000010: 96 82 17 55 81 A8 FC 60  E5 E1 3C 4D 8B 39 BA ED  ...U...`..<M.9..
00000020: B0 75 02 CC 54 0A A2 A9  98 94 9A 7B E2 3E 4A 5B  .u..T......{.>J[
00000030: 7B 01 8F 79 8D D5 03 04  D1 79 54 28 47 17 4C 67  {..y.....yT(G.Lg
00000040: FC 36 80 6E 5C 88 34 FB  9A CE BF B6 D2 12 E7 C6  .6.n\.4.........
00000050: 7D 02 DE B4 0F 39 50 5C  C6 D0 12 F2 6A A0 B7 08  }....9P\....j...
00000060: DB 28 DC 89 34 27 92 A1  F3 ED F6 C7 15 B9 C4 F4  .(..4'..........
00000070: 6C 82 18 73 E4 18 F6 BF  EE 13 9A F7 B0 EF 78 3D  l..s..........x=
00000080: 79 12 85 47 6F 33 11 B6  D0 A0 38 A9 43 BE 40 2B  y..Go3....8.C.@+
00000090: 70 72 3A B9 58 C5 CD 92  25 C8 CA EE CE 63 32 7E  pr:.X...%....c2~
000000A0: 0D 3C 28 82 6F 50 DF F9  2F 2C 33 6E 6D B6 E5 EF  .<(.oP../,3nm...
000000B0: 1B DE DE 87 F7 BB D2 01  93 CE A6 A4 D2 BE 6A AE  ..............j.
000000C0: 2C 2F EF 6B DD 93 96 41  2A F3 52 55 FD A6 97 96  ,/.k...A*.RU....
000000D0: 19 D9 3B 9D 92 F2 45 38  B7 36 CD 73 0D D5 0C 74  ..;...E8.6.s...t
000000E0: 15 09 EC E0 BB 04 3F EC  FB 12 5B B8 B8 DC E0 25  ......?...[....%
000000F0: C1 87 33 C1 5A 64 2F F6  B4 09 1F 61 B4 17 26 DF  ..3.Zd/....a..&.
-------------------------------------------
00000000: 2C FA 43 3C 34 D0 B3 1A  63 4B 7B AF 18 2F 78 86  ,.C<4...cK{../x.
00000010: 61 5B 24 ED 13 6A 27 D8  42 15 BF 05 7A 6E D3 00  a[$..j'.B...zn..
00000020: 6C 6B C3 1F 14 59 5D 80  5E 83 02 96 6C A8 6D AC  lk...Y].^...l.m.
00000030: FE E7 97 53 0C 9C 53 05  37 89 16 55 64 B5 54 03  ...S..S.7..Ud.T.
00000040: 0F D3 15 69 FC 6F 4C 8E  6A A1 1F 20 55 B7 7D 14  ...i.oL.j.. U.}.
00000050: 56 CD 46 61 79 CE A3 5B  B4 D7 F2 16 C3 1F 8D E6  V.Fay..[........
00000060: 86 F2 C4 AA DE 1F 6B CA  A1 52 6C 8A 02 F5 CD 90  ......k..Rl.....
00000070: 26 DF D2 7B 88 88 88 43  85 EB 5F 32 F7 39 EB 35  &..{...C.._2.9.5
00000080: 22 21 00 B5 1E 71 9D 15  49 78 7E DE 70 53 93 D5  "!...q..Ix~.pS..
00000090: 96 8B DB 75 76 EF C6 EC  D4 FA 6F AF AA A3 16 39  ...uv.....o....9
000000A0: F4 E0 46 0B 35 C1 60 B3  C5 20 31 32 EC 05 8B 55  ..F.5.`.. 12...U
000000B0: EC 97 98 81 8B 7D 07 3D  A8 D5 01 30 C1 53 0B 28  .....}.=...0.S.(
000000C0: 9D A9 92 1F 7D 7C E3 53  5C BD D1 ED E9 A5 61 01  ....}|.S\.....a.
000000D0: 7B 15 37 5B A4 5B 78 43  33 A1 C3 BB 9C DE C8 F5  {.7[.[xC3.......
000000E0: 3C 20 4E 90 DB B8 60 21  4A 1C 97 2F 1E 9E D5 B6  < N...`!J../....
000000F0: B6 1A 2D 59 52 52 7D 7E  BC 97 24 0D F1 36 D8 0F  ..-YRR}~..$..6..
b1pos : 0x273
00000000: 7E 6B FB FE 3E 99                                 ~k..>.
b1mutelen : 0x99730e88 
b1posend : 0x-988ffdd5 
ptraes : 0x-988ffdd6
00000000: 8E EF 90 1B 37 F1 9C D5  43 71 A2 21 70 F8 E7 22  ....7...Cq.!p.."
00000010: 5B 73 A2 77 F5 F5 93 76  68 C4 22 FB 2F 0A 03 70  [s.w...vh."./..p
size: 0x132030c5e
blocks : 0x99730f
00000000: 09 62 E9 16 1D A0 9A 9B  2D E2 D7 0B 11 32 0A FA  .b......-....2..
00000010: 36 1B F0 5A 56 6F 7E 85  48 6F 7E 81 88 85 16 4E  6..ZVo~.Ho~....N
00000020: 9E BF DB 74 39 D9 0A BC  C0 73 B6 DD 71 8D 95 99  ...t9....s..q...
00000030: 36 84 48 66 5E EE C6 5D  CE 8A 4D 49 7A C6 A7 2E  6.Hf^..]..MIz...
00000040: 85 05 D6 49 0C 3C 00 05  BB 5C 8B DA 59 19 B3 8A  ...I.<...\..Y...
00000050: 3C EC F2 C9 E1 87 59 73  6E 17 82 60 30 A1 7F 33  <.....Ysn..`0..3
00000060: 43 F0 76 4A 5D 29 23 FD  3C 81 7E 6E C8 2B 59 47  C.vJ])#.<.~n.+YG
00000070: 0D EE 7D 71 B5 13 DD 23  73 C3 15 D2 F3 9C DE 02  ..}q...#s.......
00000080: 19 CE 74 9A 97 C2 DB FA  30 70 2B B5 90 F0 7B 65  ..t.....0p+...{e
00000090: F3 64 BE 57 D0 21 BC 32  3E CF 12 54 07 9D DC 8E  .d.W.!.2>..T....
000000A0: BC A4 82 E7 E1 69 FF 36  DD 26 52 E2 77 76 9F 4A  .....i.6.&R.wv.J
000000B0: 75 6F 8A FF 0E F3 F2 9F  40 97 91 2F E9 21 3E A7  uo......@../.!>.
000000C0: 97 22 D7 69 9A 09 CD 30  A5 94 6C C7 EC 6B C0 D9  .".i...0..l..k..
000000D0: 86 AF 94 62 B1 64 E1 45  0D 24 D1 81 62 3F 47 A1  ...b.d.E.$..b?G.
000000E0: 94 0C EF 6B CC 8A 9E DF  73 E9 09 6E B6 2C 4E 53  ...k....s..n.,NS
000000F0: 7A FD A2 99 43 78 E9 BE  39 A5 70 DB 80 AE 93 B0  z...Cx..9.p.....
Traceback (most recent call last):
  File "bli223dcryptex.py", line 140, in <module>
    aes = AES.new(aesk.decode('hex'), AES.MODE_CBC, IV)
  File "/usr/lib/python2.7/encodings/hex_codec.py", line 42, in hex_decode
    output = binascii.a2b_hex(input)
TypeError: Non-hexadecimal digit found
```

**Comment by pedro-n-rocha** [comment]
Hi , thanks 

You are right VANT boards are different will try to understand the new header format 

`********* fw fixed header decoding *********************************************************************

 [ptr :          ] filname           : TG588v_r10.5.8.E-vant-c_A1_CP.bli
 [ptr : 000      ] imagetype         : BLI223S40
 [ptr : 006      ] FIACODE           : S4
 [ptr : 020      ] branding          : 0
 [ptr : 028      ] flag??            : 00000000
 [ptr : 032      ] version           :
 [ptr : 040      ] hdrlength         : 0x00000169
 [ptr : 044      ] datalength        : 0x00e4f9ba
 [ptr : 048      ] crc32             : 0c733821
 [ptr :          ] computedhash      : ff3df69c1db45c8bcbad2af4081dc41c842b158f
 [ptr :          ] decryptedhash     : 1702e956420345296b64a2bba1cdf6acd3dd2f8d1a14c0fc00293edb037a1c
 [ptr :          ] integritycheck    : False
 [ptr :          ] aeskey            : b723cbe013b35f3c0f6350eb7d49d7aa69bd257fc55fff388135b415d0679f8b
 [prt : 0xe4fb23 ] footer            :
 [ptr : 362      ] imagetype         : MUTE
 [ptr : 310      ]  undefined : 1ebcc5a2
 [ptr : 316      ] board             : VANT-C
 [ptr : 324      ] model1            : MediaAccess TG588v
 [ptr : 344      ] model2            : TG588v
 [ptr : 352      ] ?????             : 200

********************************************************************************************************
`

`********* fw fixed header decoding *********************************************************************

 [ptr :          ] filname           : vant-f_CRF687-16.3.7567-660-RG.rbi
 [ptr : 000      ] imagetype         : BLI223S70
 [ptr : 006      ] FIACODE           : S7
 [ptr : 020      ] branding          : 0
 [ptr : 028      ] flag??            : 00000000
 [ptr : 032      ] version           :
 [ptr : 040      ] hdrlength         : 0x0000016d
 [ptr : 044      ] datalength        : 0x014cf80a
 [ptr : 048      ] crc32             : d26830ce
 [ptr :          ] computedhash      : c18e4c8c6e4e65dc9a12249e8850bbaaa286ecba
 [ptr :          ] decryptedhash     : d5f03335fec60695fe
 [ptr :          ] integritycheck    : False
 [ptr :          ] aeskey            : ae8e263762e159c06baecd9dec5492010626574db3a7c2814c0097d11bb4c52a
 [prt : 0x14cf977 ] footer            :
 [ptr : 366      ] imagetype         : MUTE
 [ptr : 310      ]  undefined : 20d399c7
 [ptr : 316      ] board             : VANT-F
 [ptr : 324      ] model1            : MediaAccess TG799vac
 [ptr : 346      ] model2            : TG799vac
 [ptr : 356      ] ?????             : 200

`

**Comment by pedro-n-rocha** [comment]
Hi 
Have arrived to the conclusion that the firmware you provided is of type 0xb7 , it is a new scheme that uses an aes key to decrypt the content , there is already an aes key and a script to decrypt for another model diferent from yours (from other guys) but that key does not work on this model  , if you have access to a shell on that router , provide the contents of  /proc/keys/0x121 or something similiar and I can adapt the existing tools for we to try to make it work on that model .  

Thanks

**Comment by joushx** [comment]
Sorry, totally forgot to answer. Sadly I don't have shell access.
