### ISSUE TITLE
TG589vn

### ISSUE THREAD

**Issue by BaadMaro** [pedro-n-rocha/bli223dcryptex#4]
Hello Pedro

I'm doing some research on the router TG589vn V3 and I find that the firmware use bli223. I tried your script but it didn't work I got some crypto errors here is the scripts output 

`root@kali:~/bli223dcryptex# python bliparser.py MST-TG589vnv3-R10.5.2.F-BN.bin 
Traceback (most recent call last):
  File "bliparser.py", line 50, in <module>
    decrypted = enc.encrypt(binascii.unhexlify((hcrypt)),None)[0]
  File "/usr/lib/python2.7/dist-packages/Crypto/PublicKey/RSA.py", line 150, in encrypt
    return pubkey.pubkey.encrypt(self, plaintext, K)
  File "/usr/lib/python2.7/dist-packages/Crypto/PublicKey/pubkey.py", line 75, in encrypt
    ciphertext=self._encrypt(plaintext, K)
  File "/usr/lib/python2.7/dist-packages/Crypto/PublicKey/RSA.py", line 224, in _encrypt
    return (self.key._encrypt(c),)
ValueError: Plaintext too large
root@kali:~/bli223dcryptex# python bli223dcryptex.py MST-TG589vnv3-R10.5.2.F-BN.bin 
fdata len : 0xb3b32b
hdr len   : 0x171 
data len  : 0xb3b1ba 
totallen  : 0xb3b32b 
diffsizes : 0x0
b2mutelen : 0xb3b1b0 
b2posend : 0x17b
ptr1dec : 0x17b 
Traceback (most recent call last):
  File "bli223dcryptex.py", line 83, in <module>
    rsadec1 = rsa.encrypt(fdata[ptr1dec:ptr1dec+RSA_LEN],None)[0]
  File "/usr/lib/python2.7/dist-packages/Crypto/PublicKey/RSA.py", line 150, in encrypt
    return pubkey.pubkey.encrypt(self, plaintext, K)
  File "/usr/lib/python2.7/dist-packages/Crypto/PublicKey/pubkey.py", line 75, in encrypt
    ciphertext=self._encrypt(plaintext, K)
  File "/usr/lib/python2.7/dist-packages/Crypto/PublicKey/RSA.py", line 224, in _encrypt
    return (self.key._encrypt(c),)
ValueError: Plaintext too large
`

File header is : BLI223PR0 
Firmware link : http://products.plus-payh.co.uk/firmware/tg589/MST%20TG589vnv3%20R10.5.2.F%20BN.bin 
they use a tool i guess for updating the firmware for routers : http://products.plus-payh.co.uk/firmware/

How can i modify your code for decrypting this firmware? 

Thanks

**Comment by pedro-n-rocha** [comment]
Hi , 

this script is for older Firmwares using rsa encryption , I am not sure about your version , but there is another script made by others ,I  have it available in another repo : https://raw.githubusercontent.com/pedro-n-rocha/secr/master/blidec_enhanced.py , it identifies your fw version as "Layer type B7 being handled" , this means , unless extreme coincidence, that this firmware is AES encrypted. you need an OSCK to decrypt , your model is not listed but it is a very similiar board VDNT-1 to the research on this site : https://hack-technicolor.readthedocs.io/en/stable/Repository/   , do some exploration on how to get access on the device and get back to https://github.com/pedro-n-rocha/secr for the OSCK extraction . after you will be able to decrypt this file
